spring.application.name=banking-app

# MySQL Database Config
spring.datasource.url=jdbc:mysql://localhost:3306/bankingdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Server
server.port=8080
# ===============================
# LOGGING CONFIGURATION
# ===============================

# Set logging level
logging.level.root=INFO
logging.level.com.bank.banking.app=DEBUG

# Format logs (clean + professional)
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Reduce Spring Boot noise
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN